version: '3'

services:
  app-sql:
    build: 
      context: .
      dockerfile: Dockerfile.mssql
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    networks:
      - appnet

    
  app-api:
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings:DefaultConnection=Server=app-sql,1433;Database=180101;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 5001:80
    networks:
      - appnet

networks:
  appnet:
    driver: bridge