name: Windows Forms Build

on:
  push:
    branches:
      - master
      - main
    paths:
      - .github/workflows/winforms-build.yml
      - Pelikula.WINUI/**
  pull_request:
    branches:
      - '*'
    paths:
      - .github/workflows/winforms-build.yml
      - Pelikula.WINUI/**

jobs:
  build:
    strategy:
      matrix:
        targetplatform: [x86, x64]

    runs-on: windows-latest
    
    env:
      Solution_Path: Pelikula.WINUI\Pelikula.WINUI.csproj
      Actions_Allow_Unsecure_Commands: true

    steps:
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0

    - name:  Restore the Wpf application to populate the obj folder
      run: msbuild $env:Solution_Path /t:Restore /p:Configuration=$env:Configuration /p:RuntimeIdentifier=$env:RuntimeIdentifier
      env:
        Configuration: Debug
        RuntimeIdentifier: win-${{ matrix.targetplatform }}

    - name: Build the Windows Application Packaging Project (wapproj) 
      run: msbuild $env:Solution_Path /p:Platform=$env:TargetPlatform /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:BuildMode /p:AppxBundle=$env:AppxBundle /p:PackageCertificateKeyFile=$env:SigningCertificate /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
      env:
        AppxBundle: Never
        BuildMode: SideLoadOnly
        Configuration: Release
        TargetPlatform: ${{ matrix.targetplatform }}